### ISSUE TITLE
Support errorf assertions for Hugo 0.62.0+

### ISSUE THREAD

**Issue by manixate** [manixate/jest-hugo#20] opened 2021-09-23 04:54 UTC
Hugo 0.62.0+ doesn't log `errorf` output in the HTML output. This makes it harder for us to assert on the output. Add support for asserting on such versions.
One approach is to get the log output and map it somehow to the test. This is not simple as we don't get any file line coordinates in the output.

**Comment by jaaufauvre** [comment] 2021-09-24 11:35
Caused by https://github.com/gohugoio/hugo/issues/6653

**Comment by manixate** [comment] 2021-09-27 06:23
The issue is compounded by the fact that Hugo suppresses repeated error/warn logs from a single file. e.g. if you want to assert on an error string "this is an error" in multiple test cases in your test file, then Hugo will only output it once. This makes it impossible to figure out what was the error output. 

I had rewrote the error assertion logic (WIP) in this `feature/hugo-errorf-assertion` branch to read from the logs and assert on the test but the missing log lines are making it hard to make it fully reliable. This will only work if you have one file per error test which is not ideal. The only solution is to get that change reverted or submit a PR that would allow Hugo to output errors are before with a configuration.

**Comment by jaaufauvre** [comment] 2021-11-25 08:17
Fixed in v1.1.0

**Closed by jaaufauvre** 2021-11-25 08:17 UTC
